services:
  transcoder-api:
    container_name: transcoder-api
    image: ghcr.io/bob-park/transcoder-api
    build:
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64